#!/bin/bash
# submit this script to prodLongHost queue: bsub -q "prod.long" < test2.lsf

#BSUB -q dev
#BSUB -n 20
#BSUB -u "delucmat@students.zhaw.ch"
#BUSB -N
#BSUB -R "span[ptile=10]"

module load Anaconda3/2018.12-rhel-7  

export PATH=$PATH:/dataT/dlc/tcga/colorectal/bam_files/primary_tumor

chmod +x ./reference-based_map_sort_filter.sh
chmod +x ./reference-based_STR_calling_TR-annotation.sh

